apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-payment
  template:
    metadata:
      labels:
        app: ms-payment
    spec:
      containers:
      - name: ms-payment
        image: anaccampos/ms-payment:latest
        ports:
          - containerPort: 3040
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 400Mi
      imagePullSecrets: Never
      restartPolicy: Always