apiVersion: v1
kind: Service
metadata:
  name: ms-payment-service
  namespace: default
  labels:
    name: ms-payment
    app: service
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 4004
    targetPort: 4004
  externalIPs:
  - 192.168.49.2
  selector:
    app: ms-payment
